import type { Campground } from "./types";

export const campgrounds: Campground[] = [
  {
    id: "pine-ridge",
    name: "Pine Ridge Camp",
    area: "Gapyeong",
    landscape: "Lakeside · Forest",
    coordinates: [127.455, 37.707],
    score: 92,
    driveMinutes: 140,
    distanceKm: 118,
    price: 85000,
    highC: 12,
    lowC: 4,
    rainChance: 18,
    gustKph: 26,
    facilities: ["Toilet", "Water", "Fire pit"],
    dogFriendly: true,
    status: "best",
    reason: "A quiet forest edge, dog-friendly grounds, and a lakeside trail—all within your drive limit.",
    tradeoff: "The overnight low is colder than your sleeping bag comfort rating.",
    image: "",
    source: "Loading verified public campground data",
    checkedAt: "Just now",
    quiet: 82,
    wild: 72,
  },
  {
    id: "forest-haven",
    name: "Forest Haven",
    area: "Yangpyeong",
    landscape: "Cedar forest · Creek",
    coordinates: [127.612, 37.522],
    score: 86,
    driveMinutes: 105,
    distanceKm: 83,
    price: 72000,
    highC: 15,
    lowC: 9,
    rainChance: 12,
    gustKph: 14,
    facilities: ["Toilet", "Shower", "Water", "Power"],
    dogFriendly: true,
    status: "safe",
    reason: "Warmer overnight temperatures and complete facilities make this the easiest first trip.",
    tradeoff: "More popular and less secluded than Pine Ridge.",
    image: "",
    source: "Loading verified public campground data",
    checkedAt: "Just now",
    quiet: 55,
    wild: 38,
  },
  {
    id: "moonlit-valley",
    name: "Moonlit Valley",
    area: "Hongcheon",
    landscape: "Valley · Dark sky",
    coordinates: [127.776, 37.718],
    score: 88,
    driveMinutes: 188,
    distanceKm: 154,
    price: 64000,
    highC: 11,
    lowC: 3,
    rainChance: 8,
    gustKph: 21,
    facilities: ["Toilet", "Water"],
    dogFriendly: true,
    status: "wild",
    reason: "The strongest dark-sky setting and quietest site in the shortlist.",
    tradeoff: "It is outside your preferred drive time and needs colder-weather gear.",
    image: "",
    source: "Loading verified public campground data",
    checkedAt: "Just now",
    quiet: 95,
    wild: 91,
  },
  {
    id: "riverstone-camp",
    name: "Riverstone Camp",
    area: "Pocheon",
    landscape: "River · Meadow",
    coordinates: [127.247, 37.918],
    score: 78,
    driveMinutes: 112,
    distanceKm: 91,
    price: 76000,
    highC: 13,
    lowC: 6,
    rainChance: 42,
    gustKph: 35,
    facilities: ["Toilet", "Water", "Store"],
    dogFriendly: false,
    status: "risk",
    reason: "Good river access and a short drive.",
    tradeoff: "Dogs are not permitted and stronger gusts are forecast.",
    image: "",
    source: "Loading verified public campground data",
    checkedAt: "Just now",
    quiet: 64,
    wild: 52,
  },
  {
    id: "cedar-slope",
    name: "Cedar Slope",
    area: "Namyangju",
    landscape: "Mountain · Forest",
    coordinates: [127.294, 37.694],
    score: 81,
    driveMinutes: 74,
    distanceKm: 58,
    price: 93000,
    highC: 14,
    lowC: 8,
    rainChance: 23,
    gustKph: 17,
    facilities: ["Toilet", "Shower", "Water"],
    dogFriendly: true,
    status: "verify",
    reason: "The closest quiet forest option with a comfortable overnight low.",
    tradeoff: "Pet policy needs confirmation and the nightly price is higher.",
    image: "",
    source: "Loading verified public campground data",
    checkedAt: "Just now",
    quiet: 70,
    wild: 48,
  },
];

export const seoul: [number, number] = [126.978, 37.5665];
